# name: Deploy Nuxt

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Проверка кода
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Копирование файлов в рабочую папку на сервере
#         run: |
#           rsync -av --delete . /root/frontend/
#           cp /root/.env.production.front /root/frontend/.env

#       - name: Пересборка и рестарт Nuxt
#         run: |
#           cd /root/
#           docker compose build nuxt
#           docker compose stop nuxt
#           docker system prune -f
#           docker image prune -a -f
#           docker compose up -d nuxt
